name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: php
          bump-minor-pre-major: true
